Repository mozilla/browserid-verifier, pull requests merged in 2018-07, with the labels that each got.

#108 v0.9.3
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#110 chore(deps): Build on node v10 by default.
  .travis.yml
  Dockerfile
  lib/v1.js
  lib/v2.js
  npm-shrinkwrap.json
  package.json
  tests/aaa-enable-coverage.js
  tests/lib/test-server.js
  tests/lib/verifier.js
  tests/zzz-report-coverage.js
Labels: waffle:review

#111 v0.9.4
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#109 feat(ci): update to circle 2
  .circleci/config.yml
  circle.yml
Labels: train-118, waffle:review
